export const PermanentUpgradeIdData  = [
    'More XP',
    'More Gold',
    'Increased Drop Chance',
    'Increased Movement Speed',
    'Reduces Boss HP',
    'Increased Energy Points',
    'Increased Monster Count',
    'Longer Buff Duration',
    'Additional Mercenary Slot',
    'More first-kill loot',
    'Red Priestess Energy Heal',
    'Forbidden Knowledge',
    'Longer Farm Map Timer',
    'Reduced Farm Map Clear Requirement',
    'Guardian Shield',
    'Mastery Of The Elements',
    'Quick Slash',
    'Target Practice',
    'No Mercy',
    'Magic Echo',
    'Mercenary Power',
    'Arcane Wisdom',
    'Basic Healing Auto Hit Ability'
];
